### ISSUE TITLE
Writing a vscode extension for simple.

### ISSUE THREAD

**Issue by Youngestdev** [simple-lang/simple#13]
Could someone help write a Visual Studio code  extension for  simple code linting and completion here ?. Writing SIMPLE in vscode looks like writing plain text. Someone could volunteer :tada: .

**Comment by Thecarisma** [comment]
Bad i can't help because i don't use VS Code. You can create an extension folder in the **examples** repo 
with name **ide-extensions** to commit the code and other IDE extensions

**Comment by Youngestdev** [comment]
I'd love to work on that but I'm currently tied down.

**Comment by Thecarisma** [comment]
That is a great idea @appcypher and very important too, i will commence working on it right away, i will also be part of the environments

**Comment by devamaz** [comment]
Can I work on this

**Comment by Youngestdev** [comment]
Yes, you're very free 😊😊. PRs are welcomed. Be sure to read the
contributors guide 👍.

**Comment by appcypher** [comment]
Is anyone still working on this? I think I may just work on this myself.
I have some experience with vim, vscode, sublime and atom syntax highlighting.
@devamaz are u still working on this?

**Comment by Youngestdev** [comment]
Ah well.. I don't know if @devamaz is working on it but it's a great idea
to work on it.

**Comment by appcypher** [comment]
The simple extension for vscode has been created. This is only for syntax highlighting but more improvements can be made to it. 

You can install the extension now straight from vscode. Just search `simple` or type `ext:sim` to narrow the search.

The project is hosted here.
https://github.com/appcypher/simple-vscode

And this is it on the marketplace. 
https://marketplace.visualstudio.com/items?itemName=appcypher.simple

**Comment by Thecarisma** [comment]
Wow that great trying it at once

**Comment by appcypher** [comment]
Cool. Drop any issue you find.

**Comment by Youngestdev** [comment]
Nice work. I'll be off develop for a day or two but I'll fork repo and see
what we can do. Thanks !

**Comment by appcypher** [comment]
I guess we can close this issue now

**Comment by Youngestdev** [comment]
Yes and thanks for the extension. I'll be closing this issue.
