### ISSUE TITLE
Issue installing and running Simple on Ubuntu

### ISSUE THREAD

**Issue by devamaz** [simple-lang/simple#14]
Have issue installing and running Simple on my  Ubuntu machine after downloading linx version form sourceforge.io, I try follow the command on the README but no says no file. So I try cloning and follow  the README instruction, everything seems to work but if I type simple in the terminal it says command not found. Pls need help on proper installation. Thanks

**Comment by Youngestdev** [comment]
Hi Ahmad, we're currently working to fix the issue of adding **simple** to
global path. So to use simple, you'll have to be in the directory where
simple is installed e.g
```sh
$ cd simple/bin & simple
```
Let me know if that works 👍

**Comment by devamaz** [comment]
After downloading from sourceforge.io what is the next thing for me to do.

**Comment by Youngestdev** [comment]
I'd advise you download it from the release section. Then follow the readme.

**Comment by devamaz** [comment]
@Youngestdev ok have download and navigate to the folder with my terminal what next

**Comment by devamaz** [comment]
still get same error

**Comment by Thecarisma** [comment]
download the zip [here](https://sourceforge.net/projects/simple-lang/files/s0.3.302/) unzip it in any folder, 
```
> cd simple0.3.302-linux/bin
> ./simple
```
Sorry for the inconvenience, by next release it should be available using **yum** and **apt-get** on linux distros

**Comment by devamaz** [comment]
![simple](https://user-images.githubusercontent.com/25336847/40802387-5c2051b2-650d-11e8-9f77-d078e7a1286a.png)

**Comment by Thecarisma** [comment]
yes you did it you can run it from that folder now @devamaz 
create a file hello.sim with content 
`display "Hello world"`

> ./simple hello.sim

or choose an [example](https://github.com/simple-lang/examples) from the examples repo
We ll look into a clean install and build method on Ubuntu with **apt** by next release. 
You can open a new issue anytime you face any more problem 
Thank you for taking your time, i ll close the issue now

**Comment by Youngestdev** [comment]
The examples repo for Linux is different... I'll update it soon 🙏.

**Comment by Thecarisma** [comment]
@devamaz reinstall simple-lang from the source by cloning the repo and build with the Linux-Build.sh to install simple-lang on your system and allow simple to execute from any folder in your Linux System

**Comment by Youngestdev** [comment]
@Thecarisma, I think I'll have to build/modify the build.sh to suit Debian systems.

**Comment by Thecarisma** [comment]
you can write another build script for debian using the format of the **Linux-Build.sh**

**Comment by Youngestdev** [comment]
Yup. I'll just rewrite one like I did previously
