### ISSUE TITLE
FullTick module ( GUI ) for Linux OS.

### ISSUE THREAD

**Issue by Thecarisma** [simple-lang/simple#16]
The fulltick dynamic module for simple-lang is a port of the fltk C++ gui library.  To build the dynmic module it has to be compiled against the simple.so and the fltk shared library

**Comment by Thecarisma** [comment]
Author : @Youngestdev <img src="https://avatars3.githubusercontent.com/u/31009679?s=88&v=4&width=70&height=70" width="20" height="20" /> 

So how do we accomplish this ? I have fltk installed in my OS.

**Comment by Thecarisma** [comment]
Author : @iamcoderisk <img src="https://avatars2.githubusercontent.com/u/15240156?s=88&v=4&width=70&height=70" width="20" height="20" /> 

How far have you gone with it?

**Comment by Thecarisma** [comment]
Author : @Youngestdev <img src="https://avatars3.githubusercontent.com/u/31009679?s=88&v=4&width=70&height=70" width="20" height="20" /> 

Well, real progress will start next week 😎.

**Comment by Thecarisma** [comment]
Author : @Youngestdev <img src="https://avatars3.githubusercontent.com/u/31009679?s=88&v=4&width=70&height=70" width="20" height="20" /> 

There's a  new update. It's been fixed already and currently undergoing further testing. Cheers :tada:

**Comment by Thecarisma** [comment]
To build the **fulltick GUI module** for linux, the libfltk library will have to be built from source as a shared library instead of static. The following step will successfully build the module
 > **Building the libfltk as shared library**
   - ./configure --enable-shared
   - sudo make
   - sudo make install

then the lib fltk should be installed on the system as a shared library rather than a static library and can be statically linked during compilation. 
The next step assume you have already have simple-lang installed on your linux. If you have installed simple-lang from source the simple.so will be visible in the default **/lib/** or **/usr/local/lib** to compilers and linker using the -L flag e.g `-Lsimple.so` and can be linked for compilation. 

 > **Build the fulltick.so dynamic module for simple-lang** 
   - cd [simple/modules/dynamic_modules/fulltick](https://github.com/simple-lang/simple/tree/master/modules/dynamic_modules/fulltick)
   -  g++ -shared -I/usr/local/include -I/usr/local/include/FL/images -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT -o 'fulltick' './fulltick.cpp' './fulltick_delegate.cpp' /usr/local/lib/libfltk.a -lpthread -ldl -lm -lX11 -Lsimple.so
   - sudo install fulltick.so $(DESTDIR)$(PREFIX)/simple/$(VERSION)/modules/modules/dynamic_modules/

NOTE : You might need to put the last line in a make file for efficiency or you can review the location of the previously installed dynamic module **[sudo find -name archiver.so]** and simply copy the fultick.so module to same folder. Or just execute the makefile in the **[simple/modules/dynamic_modules/fulltick](https://github.com/simple-lang/simple/tree/master/modules/dynamic_modules/fulltick)** directory 

 > **Build the fulltick.so dynamic module for simple-lang with make file** 
   - cd [simple/modules/dynamic_modules/fulltick](https://github.com/simple-lang/simple/tree/master/modules/dynamic_modules/fulltick)
   - sudo make -f [Makefile-Linux.mk](https://github.com/simple-lang/simple/blob/master/modules/dynamic_modules/fulltick/Makefile-Linux.mk)

You can try one of the GUI examples to confirm the fulltick module installation

**Comment by Youngestdev** [comment]
Well, this isn't working because an error occurs after running the examples.
```
simple: symbol lookup error: /simple//s0.3.34/modules/dynamic_modules/fulltick.so: undefined symbol: XFixesQueryExtension
```
I'm still trying to figure out what the problem is.

**Comment by Thecarisma** [comment]
> **`simple: symbol lookup error: /simple//s0.3.34/modules/dynamic_modules/fulltick.so: undefined symbol: XFixesQueryExtension`**

should be resolved by installing libX library family. Use the command bellow to install libX on the machine

> **`sudo apt-get install libx11-dev`**

usually the error should disappear after successfully installing the libX.
If it still persist run the **./configure** file in the fltk-source on your machine to detect the missing library then the library should be install using **apt-get**

**Comment by Youngestdev** [comment]
I'll just try it and see.

**Comment by Youngestdev** [comment]
I've fixed it. The problem was that some flags needed for full fltk support for simple weren't added in the makefile so I added them . I'll commit soon.

**Comment by iamcoderisk** [comment]
Wonderful!! Bravo man...
