### ISSUE TITLE
Unable to link globally on linux

### ISSUE THREAD

**Issue by Youngestdev** [simple-lang/simple#2]
Hi, I'm unable to add simple as a compiler to the global set. I mean to make it accessible in all corners. Any help ? I'm a Linux user... 

In npm, we have something like...
```
npm link
```

**Comment by iamcoderisk** [comment]
Have you sorted this out?

**Comment by Thecarisma** [comment]
Not at all

**Comment by appcypher** [comment]
If I'm correct, @Youngestdev wants to access `simple` command from anywhere? (Correct me if I'm wrong). If that's the case, the bash build script should add simple's exe to /usr/local/bin.

**Comment by Youngestdev** [comment]
Oh well. I've done that but didn't work. It'll be good to give it a try.
:tada:

**Comment by appcypher** [comment]
Would have tried but I don't have a Linux machine.
I think that is the standard procedure for Linux systems. It's surprising that it doesn't work.

**Comment by Youngestdev** [comment]
Suprised as well. Continuous testing are still ongoing.

**Comment by Youngestdev** [comment]
Great work we've made it global. The module call is the only one remaining 😊🕺

**Comment by Youngestdev** [comment]
This is resolved so I'll close it.

**Comment by appcypher** [comment]
Shouldn't the module call problem be added as a new issue with a milestone on it.
The module call doesn't work for me, perhaps I haven't gotten the hang of it.

**Comment by Thecarisma** [comment]
Are you sure the module is installed at all as you use MAC, the current mac script does not build the modules nor add the modules folder to path, no access to a MAC PC will delay providing a very efficient build script.
If you want to build the modules and the dynamic modules you can review the Linux-Build.sh script for a lead

**Comment by Youngestdev** [comment]
I think the call module error @appcypher  is receiving is as a result of the module not building. Well, like @Thecarisma said. It'll be good if you could fix that as you're a Mac user.
