### ISSUE TITLE
Docs link returns a 404

### ISSUE THREAD

**Issue by isocroft** [simple-lang/simple#26]
This [link](https://github.com/simple-lang/simple/docs) which is on the README.md links to a GitHub 404 page. The correct link should be [this](https://github.com/simple-lang/simple/tree/master/docs). Can we have this corrected ?

**Comment by appcypher** [comment]
You can create a PR for that. But it would be faster if the core devs make a quick fix.
@Thecarisma @Youngestdev

**Comment by Thecarisma** [comment]
fixed

**Comment by appcypher** [comment]
I like your new docs by the way. Very informative. 👍

**Comment by Thecarisma** [comment]
All the thanks to @Youngestdev

**Comment by isocroft** [comment]
Nice! Since this is fixed i'll close
