### ISSUE TITLE
Display should print trailing newline or new print function be created

### ISSUE THREAD

**Issue by appcypher** [simple-lang/simple#27]
Currently the `display` magic function doesn't print a newline after its arguments, which leads to the need to sprinkle `crlf` variable about in the code. As a result, the following code prints shows its results as `Hello worldHello simple`.
```nim
display "Hello world"
display "Hello simple"
```
Also`crlf`, which I believe signifies ```carriage return + linefeed```, is platform-specific.

It would be nicer if display adds a newline to the end its arguments automatically. And if one wants a display function without newline, a new function, say ```print``` or ```echo``` can be used. 

But given that there are a lot of codes with display already, an alternative solution would be to create a new function that adds newline.

**Comment by appcypher** [comment]
I'm up for working on a new function if modifying existing one is not an option

**Comment by Youngestdev** [comment]
It'll be great if you work on another one. It'll give users the opportunity to work with the one that matches their preference.

**Comment by appcypher** [comment]
Alright will do.

**Comment by appcypher** [comment]
@Youngestdev Do you have an idea where ```display``` is defined.

**Comment by Youngestdev** [comment]
Yep. It's defined in... `simple_api.c` in simple/source folder.

**Comment by Thecarisma** [comment]
As indicated by @Youngestdev  crlf is define in the **simple_vm.c** file, a new line var can be defined in there. The display is made not to print new line after characters, instead **@** will print new line after the caharacters 
```
display "Hello World" #= Hello World
@ "Hello World" #= Hello World\n

```

**Comment by Youngestdev** [comment]
This short hand style of display, should be a regular something. I think it should be used mainly in large programs

**Comment by appcypher** [comment]
@Youngestdev Would it make sense if the `@` is changed to `print` or `echo` or sth much more descriptive?
I think the `@` doesn't readily show what it means just by looking the code and that's not beginner-friendly

**Comment by Youngestdev** [comment]
The print will be okay. The `@` isn't friendly 😃😃

**Comment by Thecarisma** [comment]
It is there to reduce typing as for web so simple and html will look compatible like 
```python
#!simple -cgi
display "Hello World"
```
and
```python
#!simple -cgi
@"Hello World"
```

The print function is present in the `siimple/utilities/Console.sim` but not within the compiler **display** is the actual keyword for printing to std output and read to read from std input. 
You can check the **Console.sim** file you will find more useful blocks within it like `print() println() readlin()``

You are good to include echo into the Console.sim too

**Comment by Youngestdev** [comment]
Then, we'll go with `echo`.

**Comment by appcypher** [comment]
@Thecarisma
Okay, now I understand why you made it `@`. Will also check out the Console module.
I will probably contribute to the docs as well to make sure some of these things don't go unnoticed.

**Comment by appcypher** [comment]
@Youngestdev 
I think one can manage with Console.println for now

**Comment by Youngestdev** [comment]
Can we use the console function in GUI apps ?

**Comment by Thecarisma** [comment]
The console is limited to Windows Command Line and Terminals just to basic standard output. The console functions does not draw on the display(the os will go gaga if it tried)

**Comment by Thecarisma** [comment]
We have the fulltick(GUI) module for GUI and porting QT will also be done in future too

**Comment by Thecarisma** [comment]
The only thing that will be fix in this issue will be to have **nl = "\n"**. so we can have a nl defined within the vm that will not be platform specific

**Comment by Youngestdev** [comment]
Well, on a final note, if this won't be fixed / improved then I suggest closing this issue.
