### ISSUE TITLE
Fulltick issue

### ISSUE THREAD

**Issue by Youngestdev** [simple-lang/simple#47]
# Description - A brief one.
Error from`fulltick` dynamic module during build

> Here's a snapshot of the error.

![screenshot from 2018-10-31 16-13-33](https://user-images.githubusercontent.com/31009679/47798517-d19da500-dd28-11e8-8338-efba5a125cad.png)

## Expected behavior and actual behavior.
Smooth installation but instead there's an error from the `png_write` function and/or stream.
## Steps to reproduce the problem.
Perhaps adding a `ld` flag or installing additional libary
## Specifications - version of the project, operating system, or hardware.
+ Version - 0.3.36
+ OS- Fedora 28

## PR Supporting Fix
None yet.
> Attach the PR link if any.

**Comment by Youngestdev** [comment]
@Thecarisma, this is within your reach.

**Comment by Youngestdev** [comment]
So I figured it out, the `png_write` isn't initialised !. Commenting it out fixed the error

**Comment by Thecarisma** [comment]
That is not a solution, though for now the function is not important but i ll recommend you install `libpng` on your Fedora OS. Use this command 
```
yum install libpng-devel
```
For compiling x86 and amd64 
```
yum install libpng-devel.x86_64
```

**Comment by Thecarisma** [comment]
Don't forget to add the flag in your fulltick makefile in the **LDFLAGS** line
```
-lpng
```

**Comment by Youngestdev** [comment]
Okay, I'll do that and see the changes.

**Comment by Youngestdev** [comment]
Well, it's still the same.  `png_write` isn't declared in that scope.

**Comment by Thecarisma** [comment]
Found out the erronous function png_write is not needed. I used it for testing purpose only. You can close.

**Comment by Youngestdev** [comment]
Okay cool.
