### ISSUE TITLE
Build fails on ubuntu

### ISSUE THREAD

**Issue by sdmg15** [simple-lang/simple#57]
# Description - A brief one.
While trying to build on Ubuntu it fails due to double slash added to directories path
```
simple-lang:install-configure: building simple-lang s0.3.36 build...
rm -rf /usr//bin/simple
rm -f /usr//lib/simple.so
rm -f /usr//lib/x86_64-linux-gnu/libsimple.so
rm -f /usr//lib/x86_64-linux-gnu/libsimple.0.3.36.so
rm -R -f /usr//include/simple/
unlink /usr//lib/libsimple.so 
unlink: cannot unlink '/usr//lib/libsimple.so': No such file or directory
Makefile-Linux.mk:193: recipe for target 'uninstall' failed
make: *** [uninstall] Error 1
```
## Expected behavior and actual behavior.
Building without errors 
## Specifications - version of the project, operating system, or hardware.

```
Simple-lang version: latest
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

```
## PR Supporting Fix
None yet
> Attach the PR link if any.

**Comment by Youngestdev** [comment]
Wierd. I don't tjink that's the problem. Did you run with the `-c` option
to configure your system ? Also I'd like a full screenshot

**Comment by Thecarisma** [comment]
```
unlink /usr//lib/libsimple.so 
unlink: cannot unlink '/usr//lib/libsimple.so': No such file or directory
Makefile-Linux.mk:193: recipe for target 'uninstall' failed
make: *** [uninstall] Error 1
```

This is an expected behavior while installing on a system, the makefile tries to uninstall previous installation using the *uninstall* recipe in the makefile, if an old build has not been installed the error above occur in the makefile. 
This should in no way affect the installation as it still proceed to install simple-lang. 

You can provide a screenshot or log for further review

**Comment by sdmg15** [comment]
Well, here's a link to a session record of my terminal

https://asciinema.org/a/WLrrMYBTXcoJbsllyHUGN1Fz4

**Comment by Thecarisma** [comment]
According to your screen cast the issue is from linking with 32 bit library on a 64 bit system, add the **x64** flag to the build script command, to build for 64 bit 

```
$ sudo bash Linux-Build.sh x64 -i
```

**Comment by sdmg15** [comment]
I'm not sure the issue is there. Can you read again the log message that I posted in the initial comment ? 
The error here is due to double slash that is added to folder paths.
I just recompiled with the instructions but still get the same error .

For example check these lines 
```mkdir -p /usr//bin
mkdir -p /usr//lib
mkdir -p /usr//include/simple

```
It's trying to create the folder "/user//lib" even though we used the argument "-p" it cannot create the folder due to the incorrectness of the path.
