### ISSUE TITLE
runtime error loading fulltick

### ISSUE THREAD

**Issue by kaecy** [simple-lang/simple#61]
Trying to compile this example: https://github.com/simple-lang/simple/blob/master/examples/gui/old-obsolete/buttonsdemo.sim

Outputs:
simple0.3.36-windows64/modules/dynamic_modules/fulltick.dll
Line 23 -> RUNTIME ERROR 24 : Runtime Error Occur while loading the dynamic library!
        at callModule() in file DynamicLoader.sim
        at line 16 in file gui.sim

I'm using the release version of simple found here.

**Comment by Thecarisma** [comment]
simply dis regard the old release versions. Compile the language from source by following the instruction on the README file for latest update. A new alpha version will be release by March 1. 

Also the example you are trying to run is obsolete you should try the examples in these directory instead.
https://github.com/simple-lang/simple/tree/master/examples/gui/fulltick
https://github.com/simple-lang/simple/tree/master/examples/modules/fulltick/widgets

**Comment by Thecarisma** [comment]
The simple version 0.4.0 has been released now download it at https://simple-lang.sourceforge.io/download/ .
You can also choose to build from  source following the instructions on the README

**Comment by kaecy** [comment]
I try to run a simple program but **0.4.0** just prints the --help string. It doesn't do anything else.

**Comment by Youngestdev** [comment]
Hi, did you run it like this ?

```

simple program.sim

```

If you did and you still got a void response. Do send a snapshot.

**Comment by kaecy** [comment]
Ah! So it doesn't open anything unless it ends in a .sim. I think that needs a slight rework. So anyway it is working!
Apart from the huge boilerplate code at the top it's pretty good.
![image](https://user-images.githubusercontent.com/4354982/54041776-7725c100-41c0-11e9-9966-caf4e7de4fcb.png)

**Comment by Youngestdev** [comment]
Well not really. You can make your programs standalone program by using the `bake` environment.

Try running `bake program.sim` from your terminal and lmk the output.

**Comment by kaecy** [comment]
So first I did `bin\bake program.sim`.
Output:
```
bake 0.0.2 (December 27 2018, 09:03 PM)
simple 0.4.0
creating temp working directory...'simple' is not recognized as an internal or external command,
operable program or batch file.

simple.io.File : The File does not exists : C:\\Users\\Kaecy\\Desktop\\simple64\\program.complex
        at line 90 in __throw at throw() in file Throw.sim
        at line 424 at ensureExistence() in file Path.sim
        at line 374 at renameTo() in file Path.sim
        at line 417 at moveTo() in file bake.sim
        at line 156 at main() in file bake.sim
        at line 68 in file bake.sim
```
I don't like this. I need simple in my environment. A program should be able to get it's own path using [GetModuleFileNameA](https://docs.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-getmodulefilenamea)

So I did `path %path%;bin` because I have simple installed on my desktop. Then `bake program.sim`.
Output:
```
bake 0.0.2 (December 27 2018, 09:03 PM)
simple 0.4.0
creating wrapper code for : program...(done)
building for windows : compiling object code...gcc -m32 -c -g -MMD -MP -MF "C:\\Users\\Kaecy\\Desktop\\simple64\\program_bake\\tmp/program.bake.c.o.d" -o "C:\\Users\\Kaecy\\Desktop\\simple64\\program_bake\\tmp/program.bake.c.o" "C:\\Users\\Kaecy\\Desktop\\simple64\\program_bake\\tmp/program.bake.c"
'gcc' is not recognized as an internal or external command,
operable program or batch file.
building for windows : generating executable...'gcc' is not recognized as an internal or external command,
operable program or batch file.
(done)
removing temporary files and folders...(done)
```
I can't do this. I don't have GCC installed. But I do have Visual Studio Build Tools.

**Comment by Thecarisma** [comment]
For the boiler plate code will be taken into consideration before next release by allowing the use of the asterisk symbol `*` to import similar sub module e.g `call fulltick.*` this way all other module under fulltick will no longer be needed to be import. 

The Installer is currently not configured to add the binary folder to system path, you can do that from the command line, this will also be visited

Bake currently depends on the GCC toolchain to create an executable, this has been a major concern alternative method will be considered also in following releases which will avoid dependency on other Programs such ass GCC.
