### ISSUE TITLE
Unable to load shared library in Linux.

### ISSUE THREAD

**Issue by Youngestdev** [simple-lang/simple#8]
I've fixed the issues with calling modules and I'll write a new documentation soon but **.dll** files cannot be run in Linux. How do we solve those issues as dynamic modules depend on those files ?

**Comment by Thecarisma** [comment]
**simple** being in it infantry no dynamic module is available for platforms except windows. we are looking forward to fully support LINUX/UNIX and MAC by next release

**Comment by Youngestdev** [comment]
Okay great. Discussion is already ongoing 👌

On Apr 7, 2018 14:50, "Azeez Adewale" <notifications@github.com> wrote:

*simple* being in it infantry no dynamic module is available for platforms
except windows. we are looking forward to fully support LINUX/UNIX and MAC
by next release

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/simple-lang/simple/issues/8#issuecomment-379470685>,
or mute
the thread

**Comment by Youngestdev** [comment]
Now, the issue is working with the shared libraries instead of dynamic modules (.dll)

**Comment by Youngestdev** [comment]
This is resolved already. I'll close it.
